import Link from "next/link";
import { createMetadata } from "@/lib/metadata";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";

export const metadata = createMetadata({
  title: "Terms of Service",
  description: "MTGPlan terms of service — governing the use of our mortgage protection insurance website.",
  path: "/terms",
  noIndex: true,
});

export default function TermsPage() {
  return (
    <>
      <div className="py-8 px-4 bg-neutral-50 border-b border-neutral-200">
        <div className="max-w-3xl mx-auto">
          <Breadcrumbs
            items={[
              { label: "Home", href: "/" },
              { label: "Terms of Service", href: "/terms" },
            ]}
          />
        </div>
      </div>

      <article className="py-16 px-4">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold text-neutral-900 mb-2">
            Terms of Service
          </h1>
          <p className="text-neutral-500 mb-10">
            Last updated: March 2026
          </p>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-neutral-900 mb-3">
              Acceptance of Terms
            </h2>
            <p className="text-neutral-700 leading-relaxed">
              By accessing or using mtgplan.com (the &ldquo;Site&rdquo;), you
              agree to be bound by these Terms of Service. If you do not agree
              with any part of these terms, please do not use our website.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-neutral-900 mb-3">
              Service Description
            </h2>
            <p className="text-neutral-700 leading-relaxed">
              MTGPlan is an informational website and lead generation service
              that connects homeowners with licensed mortgage protection
              insurance agents and carriers. The information provided on this
              website is for general educational purposes only and does not
              constitute insurance advice, legal advice, or financial advice.
              Decisions about insurance coverage should be made in consultation
              with a licensed insurance professional.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-neutral-900 mb-3">
              Disclaimer — Estimates Are Illustrative Only
            </h2>
            <p className="text-neutral-700 leading-relaxed">
              Any premium estimates or quotes generated by our online tools are
              illustrative only and are not binding quotes or offers of
              insurance. Actual premiums may differ based on your age, health,
              location, the specific insurance carrier, underwriting results, and
              other factors. A licensed insurance agent will provide you with an
              actual, binding quote based on a complete application and
              underwriting review.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-neutral-900 mb-3">
              Not an Insurance Company
            </h2>
            <p className="text-neutral-700 leading-relaxed">
              MTGPlan is not an insurance company and does not underwrite
              insurance policies. We are a lead generation and referral service
              that connects consumers with licensed insurance agents and
              insurance carriers. Any insurance policy you purchase will be
              issued by a licensed insurance carrier, not by MTGPlan. MTGPlan
              bears no responsibility for the terms, conditions, or performance
              of any insurance policy issued by a third-party carrier.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-neutral-900 mb-3">
              Limitation of Liability
            </h2>
            <p className="text-neutral-700 leading-relaxed">
              To the fullest extent permitted by applicable law, MTGPlan and its
              operators, employees, and agents shall not be liable for any
              direct, indirect, incidental, special, consequential, or exemplary
              damages resulting from your use of the Site or your reliance on
              any information provided herein. This includes but is not limited
              to damages for loss of profits, goodwill, data, or other
              intangible losses, even if MTGPlan has been advised of the
              possibility of such damages.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-neutral-900 mb-3">
              Intellectual Property
            </h2>
            <p className="text-neutral-700 leading-relaxed">
              All content on this Site, including but not limited to text,
              graphics, logos, images, and software, is the property of MTGPlan
              or its content suppliers and is protected by applicable copyright
              and intellectual property laws. You may not reproduce, distribute,
              modify, or create derivative works of any content on this Site
              without our prior written consent.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-neutral-900 mb-3">
              Third-Party Links
            </h2>
            <p className="text-neutral-700 leading-relaxed">
              Our Site may contain links to third-party websites. These links
              are provided for your convenience only. MTGPlan does not endorse,
              control, or assume responsibility for the content, privacy
              practices, or terms of any third-party websites. We encourage you
              to review the terms and privacy policies of any third-party sites
              you visit.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-neutral-900 mb-3">
              Privacy
            </h2>
            <p className="text-neutral-700 leading-relaxed">
              Your use of this Site is also governed by our{" "}
              <Link
                href="/privacy-policy"
                className="text-primary hover:text-primary-light transition-colors"
              >
                Privacy Policy
              </Link>
              , which is incorporated into these Terms by reference. By using
              the Site, you consent to the data practices described in our
              Privacy Policy.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-neutral-900 mb-3">
              Governing Law
            </h2>
            <p className="text-neutral-700 leading-relaxed">
              These Terms of Service shall be governed by and construed in
              accordance with the laws of the State of Florida, without regard
              to its conflict of law principles. Any disputes arising under
              these Terms shall be subject to the exclusive jurisdiction of the
              courts located in the State of Florida.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-neutral-900 mb-3">
              Changes to These Terms
            </h2>
            <p className="text-neutral-700 leading-relaxed">
              We reserve the right to modify these Terms of Service at any time.
              Changes will be effective immediately upon posting to the Site.
              Your continued use of the Site after any changes constitutes your
              acceptance of the revised Terms. We encourage you to review these
              Terms periodically.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-neutral-900 mb-3">
              Contact Us
            </h2>
            <p className="text-neutral-700 leading-relaxed">
              If you have any questions about these Terms of Service, please
              contact us:
            </p>
            <ul className="mt-3 space-y-1 text-neutral-700">
              <li>
                Phone:{" "}
                <a
                  href="tel:4074864555"
                  className="text-primary hover:text-primary-light transition-colors"
                >
                  (407) 486-4555
                </a>
              </li>
              <li>Website: mtgplan.com</li>
            </ul>
          </section>
        </div>
      </article>
    </>
  );
}
